version: "3.8"

services:
  frontend:
    image: public.ecr.aws/z5g6c3c8/data-center-monitoring-solution:datacentermonitoringsolution-frontend
    container_name: c_web
    ports:
      - 80:3000
    restart: unless-stopped
    stdin_open : true
    tty: true
    depends_on:
      - socket
    networks:
      - data-center-network

  socket:
    image: public.ecr.aws/z5g6c3c8/data-center-monitoring-solution:datacentermonitoringsolution-socket
    container_name: c_socket
    ports:
      - 4001:4001
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://db/DataCenterDatabase
    depends_on:
      - db
    networks:
      - data-center-network
  
  backend:
    image: public.ecr.aws/z5g6c3c8/data-center-monitoring-solution:datacentermonitoringsolution-backend
    container_name: c_api
    ports:
      - 5000:5000
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://db/DataCenterDatabase
    depends_on:
      - db
    networks:
      - data-center-network

  db:
    image: mongo:4.0.28-xenial
    container_name: monogo-db
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - DataCenterDatabase:/data/db
    networks:
      - data-center-network

volumes:
  DataCenterDatabase:

networks:
  data-center-network:
    driver: bridge


