#step 1: build stage
FROM node:18.15.0-alpine3.17 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . .
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN npm run build

#step 2: production stage
FROM nginx:1.12-alpine 
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]